
'   1   2   3   4   5   6   7   8
'
'1 zaa zab zac zad zae zaf zag zah
'
'2 zai zaj zak zal zam zan zao zap
'
'3 zaq zar zas zat zau zav zaw zax
'
'4 zay zaz zba zbb zbc zbd zbe zbf
'
'5 zbg zbh zbi zbj zbk zbl zbm zbn
'
'6 zbo zbp zbq zbr zbs zbt zbu zbv
'
'7 zbw zbx zby zbz zca zcb zcc zcd
'
'8 zce zcf zcg zch zci zcj zck zcl



CLS

1
IF zaa = 0 THEN
        LET zaa = 1
        LET a = 1
        GOTO 2
END IF
IF zab = 0 THEN
        LET zab = 1
        LET a = 2
        GOTO 2
END IF
IF zac = 0 THEN
        LET zac = 1
        LET a = 3
        GOTO 2
END IF
IF zad = 0 THEN
        LET zad = 1
        LET a = 4
        GOTO 2
END IF
IF zae = 0 THEN
        LET zae = 1
        LET a = 5
        GOTO 2
END IF
IF zaf = 0 THEN
        LET zaf = 1
        LET a = 6
        GOTO 2
END IF
IF zag = 0 THEN
        LET zag = 1
        LET a = 7
        GOTO 2
END IF
IF zah = 0 THEN
        LET zah = 1
        LET a = 8
        GOTO 2
END IF
IF zai = 0 THEN
        LET zai = 1
        LET a = 9
        GOTO 2
END IF
IF zaj = 0 THEN
        LET zaj = 1
        LET a = 10
        GOTO 2
END IF
IF zak = 0 THEN
        LET zak = 1
        LET a = 11
        GOTO 2
END IF
IF zal = 0 THEN
        LET zal = 1
        LET a = 12
        GOTO 2
END IF
IF zam = 0 THEN
        LET zam = 1
        LET a = 13
        GOTO 2
END IF
IF zan = 0 THEN
        LET zan = 1
        LET a = 14
        GOTO 2
END IF
IF zao = 0 THEN
        LET zao = 1
        LET a = 15
        GOTO 2
END IF
IF zap = 0 THEN
        LET zap = 1
        LET a = 16
        GOTO 2
END IF
IF zaq = 0 THEN
        LET zaq = 1
        LET a = 17
        GOTO 2
END IF
IF zar = 0 THEN
        LET zar = 1
        LET a = 18
        GOTO 2
END IF
IF zas = 0 THEN
        LET zas = 1
        LET a = 19
        GOTO 2
END IF
IF zat = 0 THEN
        LET zat = 1
        LET a = 20
        GOTO 2
END IF
IF zau = 0 THEN
        LET zau = 1
        LET a = 21
        GOTO 2
END IF
IF zav = 0 THEN
        LET zav = 1
        LET a = 22
        GOTO 2
END IF
IF zaw = 0 THEN
        LET zaw = 1
        LET a = 23
        GOTO 2
END IF
IF zax = 0 THEN
        LET zax = 1
        LET a = 24
        GOTO 2
END IF
IF zay = 0 THEN
        LET zay = 1
        LET a = 25
        GOTO 2
END IF
IF zaz = 0 THEN
        LET zaz = 1
        LET a = 26
        GOTO 2
END IF
IF zba = 0 THEN
        LET zba = 1
        LET a = 27
        GOTO 2
END IF
IF zbb = 0 THEN
        LET zbb = 1
        LET a = 28
        GOTO 2
END IF
IF zbc = 0 THEN
        LET zbc = 1
        LET a = 39
        GOTO 2
END IF
IF zbd = 0 THEN
        LET zbd = 1
        LET a = 30
        GOTO 2
END IF
IF zbe = 0 THEN
        LET zbe = 1
        LET a = 31
        GOTO 2
END IF
IF zbf = 0 THEN
        LET zbf = 1
        LET a = 32
        GOTO 2
END IF
IF zbg = 0 THEN
        LET zbg = 1
        LET a = 33
        GOTO 2
END IF
IF zbh = 0 THEN
        LET zbh = 1
        LET a = 34
        GOTO 2
END IF
IF zbi = 0 THEN
        LET zbi = 1
        LET a = 35
        GOTO 2
END IF
IF zbj = 0 THEN
        LET zbj = 1
        LET a = 36
        GOTO 2
END IF
IF zbk = 0 THEN
        LET zbk = 1
        LET a = 37
        GOTO 2
END IF
IF zbl = 0 THEN
        LET zbl = 1
        LET a = 38
        GOTO 2
END IF
IF zbm = 0 THEN
        LET zbm = 1
        LET a = 39
        GOTO 2
END IF
IF zbn = 0 THEN
        LET zbn = 1
        LET a = 40
        GOTO 2
END IF
IF zbo = 0 THEN
        LET zbo = 1
        LET a = 41
        GOTO 2
END IF
IF zbp = 0 THEN
        LET zbp = 1
        LET a = 42
        GOTO 2
END IF
IF zbq = 0 THEN
        LET zbq = 1
        LET a = 43
        GOTO 2
END IF
IF zbr = 0 THEN
        LET zbr = 1
        LET a = 44
        GOTO 2
END IF
IF zbs = 0 THEN
        LET zbs = 1
        LET a = 45
        GOTO 2
END IF
IF zbt = 0 THEN
        LET zbt = 1
        LET a = 46
        GOTO 2
END IF
IF zbu = 0 THEN
        LET zbu = 1
        LET a = 47
        GOTO 2
END IF
IF zbv = 0 THEN
        LET zbv = 1
        LET a = 48
        GOTO 2
END IF
IF zbw = 0 THEN
        LET zbw = 1
        LET a = 49
        GOTO 2
END IF
IF zbx = 0 THEN
        LET zbx = 1
        LET a = 50
        GOTO 2
END IF
IF zby = 0 THEN
        LET zby = 1
        LET a = 51
        GOTO 2
END IF
IF zbz = 0 THEN
        LET zbz = 1
        LET a = 52
        GOTO 2
END IF
IF zca = 0 THEN
        LET zca = 1
        LET a = 53
        GOTO 2
END IF
IF zcb = 0 THEN
        LET zcb = 1
        LET a = 54
        GOTO 2
END IF
IF zcc = 0 THEN
        LET zcc = 1
        LET a = 55
        GOTO 2
END IF
IF zcd = 0 THEN
        LET zcd = 1
        LET a = 56
        GOTO 2
END IF
IF zce = 0 THEN
        LET zce = 1
        LET a = 57
        GOTO 2
END IF
IF zcf = 0 THEN
        LET zcf = 1
        LET a = 58
        GOTO 2
END IF
IF zcg = 0 THEN
        LET zcg = 1
        LET a = 59
        GOTO 2
END IF
IF zch = 0 THEN
        LET zch = 1
        LET a = 60
        GOTO 2
END IF
IF zci = 0 THEN
        LET zci = 1
        LET a = 61
        GOTO 2
END IF
IF zcj = 0 THEN
        LET zcj = 1
        LET a = 62
        GOTO 2
END IF
IF zck = 0 THEN
        LET zck = 1
        LET a = 63
        GOTO 2
END IF
IF zcl = 0 THEN
        LET zcl = 1
        LET a = 64
        GOTO 2
END IF
END





2


IF a > 1 THEN
        LET zaa = 0
END IF
IF a > 2 THEN
        LET zab = 0
END IF
IF a > 3 THEN
        LET zac = 0
END IF
IF a > 4 THEN
        LET zad = 0
END IF
IF a > 5 THEN
        LET zae = 0
END IF
IF a > 6 THEN
        LET zaf = 0
END IF
IF a > 7 THEN
        LET zag = 0
END IF
IF a > 8 THEN
        LET zah = 0
END IF
IF a > 9 THEN
        LET zai = 0
END IF
IF a > 10 THEN
        LET zaj = 0
END IF
IF a > 11 THEN
        LET zak = 0
END IF
IF a > 12 THEN
        LET zal = 0
END IF
IF a > 13 THEN
        LET zam = 0
END IF
IF a > 14 THEN
        LET zan = 0
END IF
IF a > 15 THEN
        LET zao = 0
END IF
IF a > 16 THEN
        LET zap = 0
END IF
IF a > 17 THEN
        LET zaq = 0
END IF
IF a > 18 THEN
        LET zar = 0
END IF
IF a > 19 THEN
        LET zas = 0
END IF
IF a > 20 THEN
        LET zat = 0
END IF
IF a > 21 THEN
        LET zau = 0
END IF
IF a > 22 THEN
        LET zav = 0
END IF
IF a > 23 THEN
        LET zaw = 0
END IF
IF a > 24 THEN
        LET zax = 0
END IF
IF a > 25 THEN
        LET zay = 0
END IF
IF a > 26 THEN
        LET zaz = 0
END IF
IF a > 27 THEN
        LET zba = 0
END IF
IF a > 28 THEN
        LET zbb = 0
END IF
IF a > 29 THEN
        LET zbc = 0
END IF
IF a > 30 THEN
        LET zbd = 0
END IF
IF a > 31 THEN
        LET zbe = 0
END IF
IF a > 32 THEN
        LET zbf = 0
END IF
IF a > 33 THEN
        LET zbg = 0
END IF
IF a > 34 THEN
        LET zbh = 0
END IF
IF a > 35 THEN
        LET zbi = 0
END IF
IF a > 36 THEN
        LET zbj = 0
END IF
IF a > 37 THEN
        LET zbk = 0
END IF
IF a > 38 THEN
        LET znl = 0
END IF
IF a > 39 THEN
        LET zbm = 0
END IF
IF a > 40 THEN
        LET zbn = 0
END IF
IF a > 41 THEN
        LET zbo = 0
END IF
IF a > 42 THEN
        LET zbp = 0
END IF
IF a > 43 THEN
        LET zbq = 0
END IF
IF a > 44 THEN
        LET zbr = 0
END IF
IF a > 45 THEN
        LET zbs = 0
END IF
IF a > 46 THEN
        LET zbt = 0
END IF
IF a > 47 THEN
        LET zbu = 0
END IF
IF a > 48 THEN
        LET zbv = 0
END IF
IF a > 49 THEN
        LET zbw = 0
END IF
IF a > 50 THEN
        LET zbx = 0
END IF
IF a > 51 THEN
        LET zby = 0
END IF
IF a > 52 THEN
        LET zbz = 0
END IF
IF a > 53 THEN
        LET zca = 0
END IF
IF a > 54 THEN
        LET zcb = 0
END IF
IF a > 55 THEN
        LET zcc = 0
END IF
IF a > 56 THEN
        LET zcd = 0
END IF
IF a > 57 THEN
        LET zce = 0
END IF
IF a > 58 THEN
        LET zcf = 0
END IF
IF a > 59 THEN
        LET zcg = 0
END IF
IF a > 60 THEN
        LET zch = 0
END IF
IF a > 61 THEN
        LET zbi = 0
END IF
IF a > 62 THEN
        LET zbj = 0
END IF
IF a > 63 THEN
        LET zbk = 0
END IF

press$ = INKEY$
IF press$ = "a" THEN
        END
        ELSEIF press$ = "z" THEN
        CLS
        PRINT zaa; zab; zac; zad; zae; zaf; zag; zah
        PRINT zai; zaj; zak; zal; zam; zan; zao; zap
        PRINT zaq; zar; zas; zat; zau; zav; zaw; zax
        PRINT zay; zaz; zba; zbb; zbc; zbd; zbe; zbf
        PRINT zbg; zbh; zbi; zbj; zbk; zbl; zbm; zbn
        PRINT zbo; zbp; zbq; zbr; zbs; zbt; zbu; zbv
        PRINT zbw; zbx; zby; zbz; zca; zcb; zcc; zcd
        PRINT zce; zcf; zcg; zch; zci; zcj; zck; zcl
        PRINT ""
END IF


'==============================================================

10
IF zaa + zab + zac + zad + zae + zaf + zag + zah = 1 THEN
        GOTO 20
        ELSE GOTO 1
END IF

20
IF zai + zaj + zak + zal + zam + zan + zao + zap = 1 THEN
        GOTO 30
        ELSE GOTO 1
END IF

30
IF zaq + zar + zas + zat + zau + zav + zaw + zax = 1 THEN
         GOTO 40
         ELSE GOTO 1
END IF

40
IF zay + zaz + zba + zbb + zbc + zbd + zbe + zbf = 1 THEN
        GOTO 50
        ELSE GOTO 1
END IF

50
IF zbg + zbh + zbi + zbj + zbk + zbl + zbm + zbn = 1 THEN
        GOTO 60
        ELSE GOTO 1
END IF

60
IF zbo + zbp + zbq + zbr + zbs + zbt + zbu + zbv = 1 THEN
        GOTO 70
        ELSE GOTO 1
END IF

70
IF zbw + zbx + zby + zbz + zca + zcb + zcc + zcd = 1 THEN
        GOTO 80
        ELSE GOTO 1
END IF

80
IF zce + zcf + zcg + zch + zci + zcj + zck + zcl = 1 THEN
        GOTO 100
        ELSE GOTO 1
END IF
 
'===============================================================

100
IF zaa + zai + zaq + zay + zbg + zbo + zbw + zce = 1 THEN
        GOTO 200
        ELSE GOTO 1
END IF

200
IF zab + zaj + zar + zaz + zbh + zbp + zbx + zcf = 1 THEN
        GOTO 300
        ELSE GOTO 1
END IF

300
IF zac + zak + zas + zba + zbi + zbq + zby + zcg = 1 THEN
        GOTO 400
        ELSE GOTO 1
END IF

400
IF zad + zal + zat + zbb + zbj + zbr + zbz + zch = 1 THEN
        GOTO 500
        ELSE GOTO 1
END IF

500
IF zae + zam + zau + zbc + zbk + zbs + zca + zci = 1 THEN
        GOTO 600
        ELSE GOTO 1
END IF

600
IF zaf + zan + zav + zbd + zbl + zbt + zcb + zcj = 1 THEN
        GOTO 700
        ELSE GOTO 1
END IF

700
IF zag + zao + zaw + zbe + zbm + zbu + zcc + zck = 1 THEN
        GOTO 800
        ELSE GOTO 1
END IF

800
IF zah + zap + zax + zbf + zbn + zbv + zcd + zcl = 1 THEN
        GOTO 100000
        ELSE GOTO 1
END IF

'=====================================================================

1000
IF zaa > 2 THEN
        GOTO 1
        ELSE GOTO 1500
END IF

1500
IF zab + zai > 2 THEN
        GOTO 1
        ELSE GOTO 2000
END IF

2000
IF zac + zaj + zaq > 2 THEN
        GOTO 1
        ELSE GOTO 2500
END IF

2500
IF zad + zak + zar + zay > 2 THEN
        GOTO 1
        ELSE GOTO 3000
END IF

3000
IF zae + zal + zas + aza + abg > 2 THEN
        GOTO 1
        ELSE GOTO 3500
END IF

3500
IF zaf + zam + zat + zba + zbh + zbo > 2 THEN
        GOTO 1
        ELSE GOTO 4000
END IF

4000
IF zag + zan + zau + zbb + zbi + zbp + zbw > 2 THEN
        GOTO 1
        ELSE GOTO 4500
END IF

4500
IF zah + zao + zav + zbc + zbj + zbq + zbx + zce > 2 THEN
        GOTO 1
        ELSE GOTO 5000
END IF

5000
IF zap + zaw + zbd + zbk + zbr + zby + zcf > 2 THEN
        GOTO 1
        ELSE GOTO 5500
END IF

5500
IF zax + zbe + zbl + zbs + zbz + zcg > 2 THEN
        GOTO 1
        ELSE GOTO 6000
END IF

6000
IF zbf + zbm + zbt + zca + zch > 2 THEN
        GOTO 1
        ELSE GOTO 6500
END IF

6500
IF zbn + zbu + zcb + zci > 2 THEN
        GOTO 1
        ELSE GOTO 7000
END IF

7000
IF zbv + zcc + zcj > 2 THEN
        GOTO 1
        ELSE GOTO 7500
END IF

7500
IF zcd + zck > 2 THEN
        GOTO 1
        ELSE GOTO 8000
END IF

8000
IF zcl > 2 THEN
        GOTO 10000
        ELSE GOTO 1
END IF

'=====================================================================

10000
IF zah > 2 THEN
        GOTO 1
        ELSE GOTO 15000
END IF

15000
IF zag + zap > 2 THEN
        GOTO 1
        ELSE GOTO 20000
END IF

20000
IF zaf + zao + zax > 2 THEN
        GOTO 1
        ELSE GOTO 25000
END IF

25000
IF zae + zan + zaw + zbf > 2 THEN
        GOTO 1
        ELSE GOTO 30000
END IF

30000
IF zad + zam + zav + abe + abn > 2 THEN
        GOTO 1
        ELSE GOTO 35000
END IF

35000
IF zac + zal + zau + zad + zbm + zbv > 2 THEN
        GOTO 1
        ELSE GOTO 40000
END IF

40000
IF zab + zak + zat + zbc + zbl + zbu + zcd > 2 THEN
        GOTO 1
        ELSE GOTO 45000
END IF

45000
IF zaa + zaj + zas + zbb + zbk + zbt + zcc + zcl > 2 THEN
        GOTO 1
        ELSE GOTO 50000
END IF

50000
IF zai + zar + zba + zbj + zbs + zcb + zck > 2 THEN
        GOTO 1
        ELSE GOTO 55000
END IF

55000
IF zaq + zaz + zbi + zbr + zca + zcj > 2 THEN
        GOTO 1
        ELSE GOTO 60000
END IF

60000
IF zay + zbh + zbq + zbz + zci > 2 THEN
        GOTO 1
        ELSE GOTO 65000
END IF

65000
IF zbg + zbp + zby + zch > 2 THEN
        GOTO 1
        ELSE GOTO 70000
END IF

70000
IF zbo + zbx + zcg > 2 THEN
        GOTO 1
        ELSE GOTO 75000
END IF

75000
IF zbw + zcf > 2 THEN
        GOTO 1
        ELSE GOTO 80000
END IF

80000
IF zce > 2 THEN
        GOTO 100000
        ELSE GOTO 1
END IF

















100000
CLS
PRINT zaa; zab; zac; zad; zae; zaf; zag; zah
PRINT zai; zaj; zak; zal; zam; zan; zao; zap
PRINT zaq; zar; zas; zat; zau; zav; zaw; zax
PRINT zay; zaz; zba; zbb; zbc; zbd; zbe; zbf
PRINT zbg; zbh; zbi; zbj; zbk; zbl; zbm; zbn
PRINT zbo; zbp; zbq; zbr; zbs; zbt; zbu; zbv
PRINT zbw; zbx; zby; zbz; zca; zcb; zcc; zcd
PRINT zce; zcf; zcg; zch; zci; zcj; zck; zcl

 


