CLS
1
SLEEP 1
'===========================1
IF zaa = 0 THEN
        LET zaa = 1
        GOTO 2
END IF
'===========================2
IF zab = 0 THEN
        LET zab = 1
        LET zaa = 0
        GOTO 2
END IF
'===========================3
IF zac = 0 THEN
        LET zac = 1
        LET zaa = 0
        LET zab = 0
        GOTO 2
END IF

'===========================4
IF zad = 0 THEN
        LET zad = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        GOTO 2
END IF
'===========================5
IF zae = 0 THEN
        LET zae = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        GOTO 2
END IF
'===========================6
IF zaf = 0 THEN
        LET zaf = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        GOTO 2
END IF
'===========================7
IF zag = 0 THEN
        LET zag = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        LET zaf = 0
        GOTO 2
END IF
'===========================8
IF zah = 0 THEN
        LET zah = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        LET zaf = 0
        LET zag = 0
        GOTO 2
END IF
'===========================9
IF zai = 0 THEN
        LET zai = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        LET zaf = 0
        LET zag = 0
        LET zah = 0
        GOTO 2
END IF
'===========================10
IF zaj = 0 THEN
        LET zaj = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        LET zaf = 0
        LET zag = 0
        LET zah = 0
        LET zai = 0
        GOTO 2
END IF
'===========================10
IF zak = 0 THEN
        LET zak = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        LET zaf = 0
        LET zag = 0
        LET zah = 0
        LET zai = 0
        LET zaj = 0
        GOTO 2
END IF
'===========================11
IF zal = 0 THEN
        LET zal = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        LET zaf = 0
        LET zag = 0
        LET zah = 0
        LET zai = 0
        LET zaj = 0
        LET zak = 0
        GOTO 2
END IF
'===========================12
IF zam = 0 THEN
        LET zam = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        LET zaf = 0
        LET zag = 0
        LET zah = 0
        LET zai = 0
        LET zaj = 0
        LET zak = 0
        LET zal = 0
        GOTO 2
END IF
'===========================13
IF zan = 0 THEN
        LET zan = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        LET zaf = 0
        LET zag = 0
        LET zah = 0
        LET zai = 0
        LET zaj = 0
        LET zak = 0
        LET zal = 0
        LET zam = 0
        GOTO 2
END IF
'===========================14
IF zao = 0 THEN
        LET zao = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        LET zaf = 0
        LET zag = 0
        LET zah = 0
        LET zai = 0
        LET zaj = 0
        LET zak = 0
        LET zal = 0
        LET zam = 0
        LET zan = 0
        GOTO 2
END IF
'==========================15
IF zap = 0 THEN
        LET zap = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        LET zaf = 0
        LET zag = 0
        LET zah = 0
        LET zai = 0
        LET zaj = 0
        LET zak = 0
        LET zal = 0
        LET zam = 0
        LET zan = 0
        LET zao = 0
        GOTO 2
END IF
'==========================16
IF zaq = 0 THEN
        LET zap = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        LET zaf = 0
        LET zag = 0
        LET zah = 0
        LET zai = 0
        LET zaj = 0
        LET zak = 0
        LET zal = 0
        LET zam = 0
        LET zan = 0
        LET zao = 0
        LET zap = 0
        GOTO 2
END IF
'==========================16
IF zar = 0 THEN
        LET zar = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        LET zaf = 0
        LET zag = 0
        LET zah = 0
        LET zai = 0
        LET zaj = 0
        LET zak = 0
        LET zal = 0
        LET zam = 0
        LET zan = 0
        LET zao = 0
        LET zap = 0
        LET zaq = 0
        GOTO 2
END IF
'==========================17
IF zas = 0 THEN
        LET zas = 1
        LET zaa = 0
        LET zab = 0
        LET zac = 0
        LET zad = 0
        LET zae = 0
        LET zaf = 0
        LET zag = 0
        LET zah = 0
        LET zai = 0
        LET zaj = 0
        LET zak = 0
        LET zal = 0
        LET zam = 0
        LET zan = 0
        LET zao = 0
        LET zap = 0
        LET zaq = 0
        LET zar = 0
        GOTO 2
END IF












2
         
press$ = INKEY$
IF press$ = "a" THEN
        END
END IF




CLS
PRINT zaa; zab; zac; zad; zae; zaf; zag; zah
PRINT zai; zaj; zak; zal; zam; zan; zao; zap
PRINT zaq; zar; zas; zat; zau; zav; zaw; zax
PRINT zay; zaz; zba; zbb; zbc; zbd; zbe; zbf
PRINT zbg; zbh; zbi; zbj; zbk; zbl; zbm; zbn
PRINT zbo; zbp; zbq; zbr; zbs; zbt; zbu; zbv
PRINT zbw; zbx; zby; zbz; zca; zcb; zcc; zcd
PRINT zce; zcf; zcg; zch; zci; zcj; zck; zcl
GOTO 1















